# Generated by Django 4.2.5 on 2023-10-01 17:42

from django.conf import settings

from image_app import consts, models
from django.db import migrations, models


def create_user_groups(apps, schema_editor):
    models.TierName = apps.get_model("image_app", "TierName")
    db_alias = schema_editor.connection.alias
    tiers = (consts.BASIC, consts.PREMIUM, consts.ENTERPRISE)

    for tier in tiers:
        models.TierName.objects.using(db_alias).get_or_create(name=tier)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TierName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True),)
            ],
        ),
        migrations.RunPython(create_user_groups, migrations.RunPython.noop),
    ]
