# Generated by Django 4.2.5 on 2023-10-03 18:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import image_app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_app', '0001_tiername'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='image_app.imagedata')),
                ('image', models.ImageField(upload_to=image_app.models.image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('valid_until', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_app.tiername')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=100, help_text='minimal height')),
                ('width', models.IntegerField(default=100, help_text='minimal width')),
                ('thumbnail', models.ImageField(blank=True, upload_to=image_app.models.thumbnail_path)),
                ('valid_until', models.DateTimeField()),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_app.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
